### ISSUE TITLE
Issue switching version using download URL

### ISSUE THREAD

**Issue by skylord123** [coppit/docker-xeoma#2]
Tried to switch from using the download URL for a beta version provided by Xeoma to using the latest beta. When I placed 'latest_beta' into the config file for `VERSION` it kept failing to download the latest beta. Looking at the URL it is using for the latest beta it needs to use the URL:

http://felenasoft.com/xeoma/downloads/xeoma_beta_linux64.tgz
not 
http://felenasoft.com/xeoma/downloads/xeoma_previous_versions/?get=xeoma_linux64_17.6.23.tgz

(I don't believe latest versions are able to be downloaded using the version number until they are archived from what it looks like)

Here is the error from the log:
![image](https://user-images.githubusercontent.com/3412313/27966482-9de7ba7c-62fc-11e7-9b24-aadf44afc86c.png)

Because of this I tried to place the correct URL into the version field but I kept getting an error that the current version is the correct one (despite it not being the same version):
![image](https://user-images.githubusercontent.com/3412313/27966569-ebb6e12e-62fc-11e7-913e-ee2b356232e3.png)

So my way to get around this was to set the version to `latest` to have it download `17.5.5` then I set it to the correct beta download URL and it installed just fine. 

So as far as I can see there is an issue with these things:
- latest_beta download URL is incorrect
- detecting installed version for specific URLs is not working

Can we also get this line changed to save the current installed version file to the appdata so that it can be modified if incorrect? https://github.com/coppit/docker-xeoma/blob/95c40859e605591a305bc3729c5bba310213302c/40_install_xeoma.sh#L12

**Comment by coppit** [comment]
This is a 2-for-1 issue. I've fixed both issues.
