### ISSUE TITLE
Xeoma on synology

### ISSUE THREAD

**Issue by babbahotep** [coppit/docker-xeoma#3]
Hi,

installed coppit/xeoma on synology. On start log says:
`2017-09-08 05:11:06,stdout,[Sep 08 05:11:06 AM] Config file still has the default password. Please change the password and rerun this container.
2017-09-08 05:11:06,stdout,[Sep 08 05:11:06 AM] Processing config file
2017-09-08 05:11:06,stderr,*** Running /etc/my_init.d/30_default_config_file.sh...
2017-09-08 05:11:06,stderr,*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
2017-09-08 05:06:53,stderr,*** Killing all processes...`

container stops. 
How do I get to the xeoma.conf file if the container isnt running ? 

best 
Chris

**Comment by ghost** [comment]
figured it out:
copy the xeoma.conf to the host, edit, copy it back into container.
`docker cp 9dd707327ebe5a07ef1f0a2f3ef3cf2e5b9c15f8ffef5f5a71be88d3500c943c:/config/ /docker
`
`vi xeoma.conf`
to edit press i, enter new password, save with shift-ZZ, :q!

`docker cp /docker/xeoma.conf 9dd707327ebe5a07ef1f0a2f3ef3cf2e5b9c15f8ffef5f5a71be88d3500c943c:/config`

**Comment by coppit** [comment]
No, don't do that. Next time you update the container, the file will be lost.

Map the config directory in the container to a directory in the host. See docs here: https://hub.docker.com/r/coppit/xeoma/

BTW, what's the story with Synology? I don't use it. Is there some way that I can encourage people to properly read the docs for my container?

**Comment by ghost** [comment]
Hi,

Hmm, why not ? I injected the changed config into the stopped container. It should persist shouldn’t it ?

Synology is a NAS OS that runs docker images. Thing with Synology is that if the container crashes there is no way to get to the container afaik.

I think I followed your doc to the point. On Synology when you start your container it stops with the password not changed error and there is no way to get to the config from the outside UI or SSH.

Best regards
Christian

On Sep 10, 2017, 7:10 PM -0700, coppit <notifications@github.com>, wrote:

No, don't do that. Next time you update the container, the file will be lost.

Map the config directory in the container to a directory in the host. See docs here: https://hub.docker.com/r/coppit/xeoma/

BTW, what's the story with Synology? I don't use it. Is there some way that I can encourage people to properly read the docs for my container?

**Comment by coppit** [comment]
> I injected the changed config into the stopped container. It should persist shouldn’t it ?

That's not how containers work. When you update the container, all changes inside it are lost.

> On Synology when you start your container it stops with the password not changed error and there is no way to get to the config from the outside UI or SSH.

That's why for docker containers you map the directory that contains your config. That way you can access the files from outside the container, and they will be persisted across container updates. Looking at the Synology docs, I can see that they have options for mapping the "volume". That's what you want to use. Perhaps someone on the Synology forums can help you if the docs are unclear. https://www.synology.com/en-us/knowledgebase/DSM/help/Docker/docker_container
